### ISSUE TITLE
Design/Build Common Dashboard page

### ISSUE THREAD

**Issue by GregMohr** [chingu-voyages/v42-bears-team-42#75]
This is the base dashboard that will contain the controls common to both the manager and employee dashboard components. It should consist of:
- [x] Header that includes:
  - [x] Background image. Could we crop a part of our Landing Page image?
  - [x] Current user identifier (first or first and last name).
       - This will be a dropdown giving access to profile features: change password; change email (and logout?)
  - [x] SAM logo
  - [x] Logout if we don't put it under the name dropdown
- [x] Content panel to display the individual (Manager, Employee) dashboard components

**Comment by GregMohr** [comment]
Additional components we need for this overall component are 2 modals for Change Password and Change Email address. We can go with any typical look. They should pop up, mid screen, with needed fields and button to submit request. Aya is currently working on this

**Comment by adbshiau** [comment]
Done working on it. What they look like so far:
![](https://cdn.discordapp.com/attachments/1058927370897195028/1070766960738045993/Screen_Shot_2023-02-02_at_10.05.14_AM.png)

![](https://cdn.discordapp.com/attachments/1058927370897195028/1070766960989720576/Screen_Shot_2023-02-02_at_10.05.32_AM.png)

**Comment by adbshiau** [comment]
Additional tasks:

- [ ] display user information
- [ ] modals functionality
- [ ] sign out functionality
